/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const ForgotPasswordLazyImport = createFileRoute('/forgot-password')()
const CreateNewPasswordLazyImport = createFileRoute('/create-new-password')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const ForgotPasswordLazyRoute = ForgotPasswordLazyImport.update({
  path: '/forgot-password',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/forgot-password.lazy').then((d) => d.Route),
)

const CreateNewPasswordLazyRoute = CreateNewPasswordLazyImport.update({
  path: '/create-new-password',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/create-new-password.lazy').then((d) => d.Route),
)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/create-new-password': {
      preLoaderRoute: typeof CreateNewPasswordLazyImport
      parentRoute: typeof rootRoute
    }
    '/forgot-password': {
      preLoaderRoute: typeof ForgotPasswordLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  CreateNewPasswordLazyRoute,
  ForgotPasswordLazyRoute,
])

/* prettier-ignore-end */
